version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-transactions
    ports:
      - '3000:3000' # expõe a porta 3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped
